# Generated by Django 5.2.4 on 2025-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('descr', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], default='M', max_length=1)),
                ('abilities', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], default='M', max_length=20)),
                ('Weaknesses', models.CharField(choices=[('GRASS', 'Grass'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('FLYING', 'Flying'), ('BUG', 'Bug')], max_length=20)),
            ],
        ),
    ]
